PLejeune\VideoBundle\Entity\Video:
  type: entity
  table: video
  repositoryClass: PLejeune\VideoBundle\Repository\VideoRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    title:
      type: string
      length: 255
    identifier:
      type: string
      length: 255
    preview:
      type: string
      length: 255
    platform:
      type: string
      length: 255
    enabled:
      type: boolean
    published:
      type: datetime
    checked:
      type: datetime
      nullable: true
  manyToOne:
    channel:
      targetEntity: PLejeune\VideoBundle\Entity\Channel
      joinColumn:
        name: channel_id
        referencedColumnName: id
      nullable: true
  lifecycleCallbacks: {  }
