services:
  plejeune.video.command.channel.update:
    public: true
    class: PLejeune\VideoBundle\Command\Channel\UpdateCommand
    tags:
      - { name: console.command }

  plejeune.stream.command.video.clean:
    public: true
    class: PLejeune\VideoBundle\Command\Video\CleanCommand
    tags:
      - { name: console.command }

  PLejeune\VideoBundle\Service\ChannelService:
    public: true
    class: PLejeune\VideoBundle\Service\ChannelService
    arguments: ["@service_container"]

  PLejeune\VideoBundle\Service\VideoService:
    public: true
    class: PLejeune\VideoBundle\Service\VideoService
    arguments: ["@service_container"]
