services:
  darkanakin41.video.command.channel.update:
    public: true
    class: Darkanakin41\VideoBundle\Command\Channel\UpdateCommand
    tags:
      - { name: console.command }

  darkanakin41.stream.command.video.clean:
    public: true
    class: Darkanakin41\VideoBundle\Command\Video\CleanCommand
    tags:
      - { name: console.command }

  Darkanakin41\VideoBundle\Service\ChannelService:
    public: true
    class: Darkanakin41\VideoBundle\Service\ChannelService
    arguments: ["@service_container"]

  Darkanakin41\VideoBundle\Service\VideoService:
    public: true
    class: Darkanakin41\VideoBundle\Service\VideoService
    arguments: ["@service_container"]
