<?php

/*
 * This file is part of the Darkanakin41VideoBundle package.
 */

namespace Darkanakin41\VideoBundle;

use Doctrine\Bundle\DoctrineBundle\DependencyInjection\Compiler\DoctrineOrmMappingsPass;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class Darkanakin41VideoBundle extends Bundle
{
    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub

        // With annotation configuration format
        $container->addCompilerPass(DoctrineOrmMappingsPass::createAnnotationMappingDriver(array(
            'Darkanakin41\VideoBundle\Model',
        ), array(
            realpath(__DIR__.'/Model'),
        )));
    }
}
